services:
  api:
    image: sih-api
    build:
      context: api/
      dockerfile: ./Dockerfile
    environment:
      - HF_TOKEN=${HF_TOKEN}
    devices:
      - nvidia.com/gpu=all
    ports:
      - "${API_PORT}:8000"

  client:
    image: sih-client
    build:
      context: client/
      dockerfile: ./Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "${CLIENT_PORT}:3000"
